name: Builds

on:
  push:
  pull_request:
    branches:
      - master
      - 'release/**'

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  sycl:
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/ubuntu2004_oneapi:v9
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: >
          source /opt/intel/oneapi/setvars.sh
          && cmake -B build -S .
          -GNinja
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS=-Werror
          -DACTS_BUILD_PLUGIN_SYCL=ON
          -DACTS_BUILD_UNITTESTS=ON
      - name: Build
        run: >
          source /opt/intel/oneapi/setvars.sh
          && cmake --build build --
      - name: Install 
        run: >
          source /opt/intel/oneapi/setvars.sh
          && cmake --build build -- install
      - name: Downstream configure
        run: >
          source /opt/intel/oneapi/setvars.sh
          && mkdir build-downstream && cd build-downstream &&
          cmake ../Tests/DownstreamProject
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS=-Werror
          -DCMAKE_PREFIX_PATH="${INSTALL_DIR}"
      - name: Downstream build
        run: >
          source /opt/intel/oneapi/setvars.sh
          && cmake --build build-downstream --
      - name: Downstream run
        run: >
          source /opt/intel/oneapi/setvars.sh
          && ./build-downstream/bin/ShowActsVersion
